PLAYER_RUN_SPEED = 80
PLAYER_JOG_SPEED = 60

VIEW_ANGLE_NARROW = 45
VIEW_ANGLE_NORMAL = 90
VIEW_ANGLE_WIDE = 180
VIEW_ANGLE_STEP_RANGE = 30

BALL_DECAY = 0.94  # per tick
BALL_MAX_SPEED = 3
KICKABLE_MARGIN = 0.7
KICK_POWER_RATE = 0.027

